AWSTemplateFormatVersion: "2010-09-09"
Description: Servidor gRPC simples em EC2

Resources:
  GrpcSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Access to gRPC port 50051"
      VpcId: vpc-0a1b796084f120d05
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 50051
          ToPort: 50051
          CidrIp: 0.0.0.0/0

  GrpcInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0c02fb55956c7d316
      SecurityGroupIds:
        - !Ref GrpcSecurityGroup
      KeyName: atividade
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            dnf update -y
            dnf install -y python3 python3-pip git

            # Clona o repositório
            cd /home/ec2-user
            git clone https://github.com/tulipin/projeto-distribuida.git

            # Instala dependências gRPC
            pip3 install grpcio grpcio-tools

            # Executa o servidor em background e redireciona logs
            cd projeto-distribuida
            nohup python3 server.py > server.log 2>&1 &

Outputs:
  PublicIP:
    Description: IP público da instância EC2
    Value: !GetAtt GrpcInstance.PublicIp
