AWSTemplateFormatVersion: "2010-09-09"
Description: Servidor gRPC em EC2 com Ubuntu 22.04

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: KeyPair para SSH (ex: atividade)

  RepositoryUrl:
    Type: String
    Default: "https://github.com/LeonardoPS39/atividade-grpc-cloud.git"
    Description: URL do repositório GitHub com server.py

Resources:
  GrpcSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and gRPC"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 50051
          ToPort: 50051
          CidrIp: 0.0.0.0/0

  GrpcInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: "{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}"
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref GrpcSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -xe

          # atualiza e instala Python, pip e Git
          apt-get update -y
          apt-get install -y python3 python3-pip git

          # clona código e instala dependências
          cd /home/ubuntu
          git clone ${RepositoryUrl} app
          cd app
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

          # inicia servidor gRPC em background
          nohup python3 server.py > /home/ubuntu/server.log 2>&1 &
          chown -R ubuntu:ubuntu /home/ubuntu

Outputs:
  PublicIP:
    Description: IP público da instância EC2
    Value: !GetAtt GrpcInstance.PublicIp