# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\"\x18\n\x08Mensagem\x12\x0c\n\x04nome\x18\x01 \x01(\t\"\x19\n\x08Resposta\x12\r\n\x05texto\x18\x01 \x01(\t2=\n\x0fSaudacaoService\x12*\n\x06Saudar\x12\x0f.hello.Mensagem\x1a\x0f.hello.Respostab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAGEM']._serialized_start=22
  _globals['_MENSAGEM']._serialized_end=46
  _globals['_RESPOSTA']._serialized_start=48
  _globals['_RESPOSTA']._serialized_end=73
  _globals['_SAUDACAOSERVICE']._serialized_start=75
  _globals['_SAUDACAOSERVICE']._serialized_end=136
# @@protoc_insertion_point(module_scope)
